djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

from shop import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BaseView.as_view(), name='index'),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),

]

shop/urls.py
from django.urls import path
from shop import views


urlpatterns = [

    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<int:pk>/', views.ListCategoryView.as_view(), name='category'),
    path('add_product/', views.AddProductView.as_view(), name='add_product'),
    path('delete_category/<int:pk>/', views.DeleteCategoryView.as_view(), name='delete_category'),
    path('update_category/<int:pk>/', views.UpdateCategoryView.as_view(), name='update_category'),
    path('products/<str:category>/', views.ListProductView.as_view(), name='list_product'),
    path('delete_product/<int:pk>/', views.DeleteProductView.as_view(), name='delete_product'),
    path('update_product/<int:pk>/', views.UpdateProductView.as_view(), name='update_product'),
    path('add_to_cart/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartDetailView.as_view(), name='cart'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('search/', views.search, name='search'),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name



class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)





class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

templates/add_category.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">

    </form>
{% endblock %}

templates/add_product.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

templates/add_to_cart.html
{% extends 'base.html' %}

{% block content %}
   <h1>Dodaj produkt do koszyka</h1>
    <form action="{% url 'add_to_cart' product_id %}" method="post">
        {% csrf_token %}
        <label for="quantity">Ilość:</label><br>
        <input type="number" id="quantity" name="quantity" min="1"><br>

        <input type="submit" value="Dodaj do koszyka">

    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Shop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getToken('csrftoken')

        function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");

            // Loop through the array elements
            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if (name == cookiePair[0].trim()) {
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }

            // Return null if not found
            return null;
        }

        var cart = JSON.parse(getCookie('cart'))

        if (cart == undefined) {
            cart = {}
            console.log('Cart Created!', cart)
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)

    </script>
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Strona głowna</a>
    {% if perms.shop.add_product %}
    <a class="navbar-brand" href="{% url 'add_product' %}">Dodaj Produkt</a>
    {% endif %}
{% if perms.shop.add_category %}
    <a class="navbar-brand" href="{% url 'add_category' %}">Dodaj Kategorie</a>
{% endif %}
{% if perms.shop.view_order %}
    <a class="navbar-brand" href="{% url 'orders' %}">Zamówienia</a>
{% endif %}
        {% if not user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'login' %}">Login</a>
    <a class="navbar-brand" href="{% url 'register' %}">Rejestracja</a>

        {% endif %}
{% if user.is_authenticated %}
    <a class="text-light float-right navbar-brand"> Witaj {{ user }}<br>

        <a class="navbar-brand" href="{% url 'logout' %}">wyloguj</a> </a>
{% endif %}


        <div class="form-inline my-2 my-lg-0">


            <a href="{% url 'cart' %}">
                <img id="cart-icon" src="{% static 'images/cart.png' %}">
            </a>
            <p id="cart-total">{{ cartItems }}</p>

        </div>


    <form method="GET" action="{% url 'search' %}">
        <input type="text" name="q" placeholder="Szukaj Produktu">
        <input type="submit" value="Szukaj">
    </form>
</nav>
<div class="container category-product">
    {#    {% include 'main_links.html' %}#}



<ul class="navbar  navbar-dark bg-dark c ">
    {% for item in categories %}
        <li style = "list-style: none"><a class="navbar-brand" href="{% url 'list_product' item.name %}">{{ item.name }}</a>
            {% if perms.shop.delete_category %}
                <a href="{% url 'delete_category' item.id %} ">
                    <img src="{% static 'dal.png' %}" width="20"></a>
            {% endif %}
            {% if perms.shop.update_category %}
                <a href="{% url 'update_category' item.id %} ">
                    <img src="{% static 'up.png' %}" width="20"></a>
            {% endif %}

        </li>
    {% endfor %}
</ul>
</div>


<div class="container">
    {% block content %}

    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}

    <h1>Twój Koszyk</h1>

    <form action="{% url 'order_detail' order_id %}" method="post">
        {% csrf_token %}
    <input type="submit" value="Zapłać">
    </form>




<div class="box-element">
				<div class="cart-row">
{#					<div style="flex:2"></div>#}
					<div style=""><strong>Przedmioty</strong></div>
					<div style="padding-left: 15rem"><strong>Cena</strong></div>
					<div style="padding-left: 15rem"><strong>Ilosc</strong></div>
					<div style="padding-left: 15rem"><strong>Total</strong></div>
				</div>
				{% for item in cart_items %}
				<div class="cart-row">
{#					<div style="flex:2"><img class="row-image" src=""></div>#}
					<div style="padding-left: 0rem"><p>{{item.product.name}}</p></div>
					<div style="padding-left: 15rem"><p>${{item.product.price|floatformat:2}}</p></div>
					<div style="padding-left: 15rem"><p>{{item.quantity}}</p></div>
					<div style="padding-left: 15rem"><p>{{total_price|floatformat:2}}</p></div>
				</div>
				{% endfor %}
			</div>

{% endblock %}

templates/delete_category_form.html
{% extends 'base.html' %}
{% block content %}
    Czy jestes pewien że chcesz usunąć kategorie {{ object.name }}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>

{% endblock %}

templates/delete_product_form.html
{% extends 'base.html' %}
{% block content %}
    Czy jestes pewien że chcesz usunąć produkt {{ object.name }}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>

{% endblock %}

templates/form_generic.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

templates/list_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% for product in products %}
    <h1>{{ product.name }}
        {% if perms.shop.delete_product %}
            <a href="{% url 'delete_product' product.id%} ">
                <img src="{%  static 'dal.png'%}" width="20"></a>
        {% endif %}
        {% if perms.shop.change_product %}
            <a href="{% url 'update_product' product.id%} ">
                <img src="{%  static 'up.png'%}" width="20"></a>
        {% endif %}
    </h1>
    <h2>{{ product.description}}</h2>
    <h2>{{ product.price}}</h2>
    <a href="{% url 'add_to_cart' product.id%}">Dodaj do koszyka</a>
{% endfor %}
{% endblock %}

templates/main_links.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item m-2">
                <a href="{% url 'add_category' %}">Dodaj Kategorie</a>
            </li>
            <li class="nav-item m-2">
                <a href="{% url 'add_product' %}">Dodaj Produkt</a>
            </li>
            <li class="nav-item m-2">
                <a href="{% url 'index' %}">Strona glowna</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item m-2">
                <a href="{% url 'cart' %}">Koszyk</a>
            </li>
            {% endif %}
            <li class="nav-item m-2">
                <a href="{% url 'orders' %}">Zamówienia</a>
            </li>


        </ul>
        <div>
            {% if not user.is_authenticated %}
                <ul>
            <li><a href="{% url 'login' %}">logowanie</a></li>
            <li><a href="{% url 'register' %}">rejestracja</a></li>
                </ul>
            {% else %}
               <span class="text-light float-right"> Witaj {{ user }}<br><a href="{% url 'logout' %}">wyloguj</a> </span>
            {% endif %}
        </div>

    </div>
</nav>

templates/order_detail.html
{% extends 'base.html' %}

{% block content %}


    		<div class="col-lg-6">
			<div class="box-element">
				<hr>
				<h3>Szczegół Zamówienia </h3>
				<hr>
				{% for item in order_items %}
				<div class="cart-row">
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Total:   ${{total_price|floatformat:2}}</h5>
			</div>
		</div>
{% endblock %}

templates/orders.html
{% extends 'base.html' %}

{% block content %}


<h1>Lista Zamówień</h1>
    {% for order in orders %}
        <div>
            <h2>Numer Zamówienia: {{ order.id }}</h2>
            <p>Data: {{ order.date }}</p>
            <a href="{% url 'order_detail' order.id %}">Szczegóły Zamównia</a>
        </div>
    {% endfor %}

{% endblock %}

templates/search_results.html
{% extends 'base.html' %}

{% block content %}
{% for result in results %}
	<h2>{{ result.name }}</h2>
    <h3>{{ result.description }}</h3>
    <h3>{{ result.price }}</h3>
    <a href="{% url 'add_to_cart' result.id%}">Dodaj do koszyka</a>
{% endfor %}


{% endblock %}